# Generated by Django 3.0.6 on 2020-05-24 23:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 23, 34, 57, 403005, tzinfo=utc)),
        ),
    ]
