# Generated by Django 3.0.6 on 2020-05-24 23:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20200525_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 23, 44, 48, 702005, tzinfo=utc)),
        ),
    ]
