# Generated by Django 3.0.6 on 2020-05-23 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_area', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PMCountys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PMPrjTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_type', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='PMYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PMProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('dev_attr', models.CharField(max_length=12)),
                ('line_len', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cable_len', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capacity_size', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_country_grid', models.BooleanField()),
                ('start_date', models.DateField()),
                ('commissioning_date', models.DateField()),
                ('prj_attr', models.CharField(max_length=300)),
                ('access_system_proposal', models.CharField(max_length=300)),
                ('info', models.CharField(max_length=300)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.PMCountys')),
                ('supply_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.PMAreas')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.PMYears')),
            ],
            options={
                'verbose_name': '项目规划库',
            },
        ),
    ]
