# Generated by Django 3.0.6 on 2020-05-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_auto_20200523_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pmareas',
            options={'ordering': ['prj_area'], 'verbose_name': '供电区域', 'verbose_name_plural': '供电区域'},
        ),
        migrations.AlterField(
            model_name='pmareas',
            name='prj_area',
            field=models.CharField(max_length=4, verbose_name='供电区域'),
        ),
        migrations.AlterField(
            model_name='pmcountys',
            name='county_name',
            field=models.CharField(max_length=12, verbose_name='项目县级区域'),
        ),
        migrations.CreateModel(
            name='PMPrjPreFeasibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=300, verbose_name='备注')),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.PMProjects', verbose_name='项目')),
            ],
        ),
    ]
