# Generated by Django 3.0.6 on 2020-05-24 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20200525_0734'),
        ('pm', '0003_auto_20200523_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pmprjprefeasibility',
            options={'verbose_name': '项目', 'verbose_name_plural': '2.项目可研库(内审)'},
        ),
        migrations.AlterModelOptions(
            name='pmprojects',
            options={'verbose_name': '项目', 'verbose_name_plural': '1.项目规划库'},
        ),
        migrations.AddField(
            model_name='pmprjprefeasibility',
            name='file_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.FileInfo', verbose_name='内审文件'),
        ),
        migrations.CreateModel(
            name='PMPrjPreFirstFounded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=300, verbose_name='备注')),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.PMProjects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '4.项目初设库(内审)',
            },
        ),
        migrations.CreateModel(
            name='PMPrjFirstFounded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=300, verbose_name='备注')),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.PMProjects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '5.项目初设库(省公司)',
            },
        ),
        migrations.CreateModel(
            name='PMPrjFeasibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=300, verbose_name='备注')),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.PMProjects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '3.项目可研库(省公司)',
            },
        ),
    ]
