# Generated by Django 3.0.6 on 2020-05-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_auto_20200525_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmprjprefeasibility',
            name='cable_len',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='电缆长度'),
        ),
        migrations.AddField(
            model_name='pmprjprefeasibility',
            name='capacity_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='容量大小'),
        ),
        migrations.AddField(
            model_name='pmprjprefeasibility',
            name='line_len',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='架空线路长度'),
        ),
        migrations.AddField(
            model_name='pmprjprefeasibility',
            name='total_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='总投资'),
        ),
    ]
